options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/$_JOB_NAME:latest || echo "no cache image"']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'git_commit=branch:$BRANCH_NAME sha:$SHORT_SHA'
      - '--build-arg'
      - 'env_file=cicd/env.$BRANCH_NAME'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/$_JOB_NAME:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_JOB_NAME:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_JOB_NAME:latest'
      - '-f'
      - 'cicd/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/$_JOB_NAME'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: bash
    args:
      - -c
      - |
        set -e

        IMAGE="gcr.io/$PROJECT_ID/$_JOB_NAME:$COMMIT_SHA"

        if gcloud run jobs describe $_JOB_NAME --region $_DEPLOY_REGION > /dev/null 2>&1
        then
          echo "Job exists → updating"
          gcloud run jobs update $_JOB_NAME \
            --region $_DEPLOY_REGION \
            --image "$IMAGE" \
            --quiet
        else
          echo "Job does not exist → creating"
          gcloud run jobs create $_JOB_NAME \
            --region $_DEPLOY_REGION \
            --image "$IMAGE" \
            --quiet
        fi

images:
  - 'gcr.io/$PROJECT_ID/$_JOB_NAME:latest'
  - 'gcr.io/$PROJECT_ID/$_JOB_NAME:$COMMIT_SHA'