"""links and footer shared by every job's emails"""

CHECK_SUBMISSION_URL = "https://check.arxiv.org/submit/{submission_id}"
MOD_TODO_URL         = "https://check.arxiv.org/q/todo"
MOD_TODO_TITLE       = "Your moderation todo queue"

CHECK_GUIDE_URL   = "https://arxiv-org.atlassian.net/wiki/spaces/ModRes/pages/1312915466/arXiv+Check+Start+Guide"
CHECK_GUIDE_TITLE = "How to use Check"
HOW_TO_MOD_URL    = "https://arxiv-org.atlassian.net/wiki/spaces/ModRes/pages/830767115/How+do+I+moderate+a+submission"
HOW_TO_MOD_TITLE  = "How to moderate"
MOD_HUB_URL       = "https://arxiv-org.atlassian.net/wiki/spaces/ModRes/pages/812580865/Moderator+Hub"
MOD_HUB_TITLE     = "Moderator Hub"

_FOOTER_LINE1 = "This email was generated by the moderator email system version 2.0"
_FOOTER_LINE2 = "Some of your arXiv moderation emails may look different. Throughout 2026, we will be transitioning email systems."


def render_footer() -> tuple[str, str]:
    """the guide links and system note that close out every moderator email"""
    footer_text = (
        f"{CHECK_GUIDE_TITLE}: {CHECK_GUIDE_URL} \n"
        f"{HOW_TO_MOD_TITLE}: {HOW_TO_MOD_URL} \n"
        f"{MOD_HUB_TITLE}: {MOD_HUB_URL} \n"
        f"\n"
        f"{_FOOTER_LINE1}\n"
        f"{_FOOTER_LINE2}\n"
    )
    footer_html = (
        f"<p>"
        f"<a href=\"{CHECK_GUIDE_URL}\">{CHECK_GUIDE_TITLE}</a> | "
        f"<a href=\"{HOW_TO_MOD_URL}\">{HOW_TO_MOD_TITLE}</a> | "
        f"<a href=\"{MOD_HUB_URL}\">{MOD_HUB_TITLE}</a>"
        f"</p>\n"
        f"<p>{_FOOTER_LINE1}<br>\n"
        f"{_FOOTER_LINE2}</p>\n"
    )
    return footer_text, footer_html


def check_submission_url(submission_id: int) -> str:
    """the Check page for one submission"""
    return CHECK_SUBMISSION_URL.format(submission_id=submission_id)
