# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'poetry'

      - run: poetry install

      - run: poetry run coverage run -m pytest -vv

      - run: poetry run coverage report
